import MainNav from "@/components/own/Nav/MainNav";

import StudentSidebar from "@/components/own/StudentSidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row w-full h-full">
      <div className="fixed top-0 left-0 z-50 lg:relative lg:block">
        {/* this will contain sidebar */}
        <StudentSidebar />
      </div>
      <div className="fixed top-0 w-full z-20">
        <MainNav />
      </div>
      <div className="w-full h-full flex flex-col bg-primary_background overflow-auto">
        {/* this will contain navbar and main content */}

        {children}
      </div>
    </div>
  );
}
