import MainDashboard from "@/components/own/Dashboard/MainDashboard";
import MainNav from "@/components/own/Nav/MainNav";
import Sidebar from "@/components/own/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row">
          <div>
            {/* this will contain sidebar */}
            <Sidebar />
          </div>
          <div className="w-full px-10 py-4 flex flex-col">
            {/* this will contain navbar and main content */}
            <MainNav />
            <MainDashboard />
          </div>
        </div>
      </body>
    </html>
  );
}
