import CompanySidebar from "@/components/own/CompanySidebar";
import JobCreationForm from "@/components/own/Form/JobCreationForm";

import MainNav from "@/components/own/Nav/MainNav";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row w-full h-full">
      <div className="fixed top-0 left-0 z-50 lg:relative lg:block">
        {/* this will contain sidebar */}
        <CompanySidebar />
      </div>
      <div className="w-full h-full flex flex-col bg-primary_background">
        {/* this will contain navbar and main content */}
        <MainNav />

        {children}
        <div className="mt-20"> hello</div>
        <JobCreationForm />
      </div>
    </div>
  );
}
