// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmjAEleMtHfTT38K15EXGTbqwgN9Cc-6w',
    appId: '1:225265442811:android:44bf8ac65ccfd622dab55e',
    messagingSenderId: '225265442811',
    projectId: 'placenext-17bb0',
    storageBucket: 'placenext-17bb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR7eCVT7Odnn7LKt3qaOmf68k6Xv6axX8',
    appId: '1:225265442811:ios:cb2e46d73e8a6b0edab55e',
    messagingSenderId: '225265442811',
    projectId: 'placenext-17bb0',
    storageBucket: 'placenext-17bb0.appspot.com',
    iosClientId: '225265442811-jkh9bm5fjgma3gbtuhc8ckh8ke22bm8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR7eCVT7Odnn7LKt3qaOmf68k6Xv6axX8',
    appId: '1:225265442811:ios:cb2e46d73e8a6b0edab55e',
    messagingSenderId: '225265442811',
    projectId: 'placenext-17bb0',
    storageBucket: 'placenext-17bb0.appspot.com',
    iosClientId: '225265442811-jkh9bm5fjgma3gbtuhc8ckh8ke22bm8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6WJfXLAuGHaNAcVcpXEzooDUJWuH-op8',
    appId: '1:225265442811:web:e204ee8f0034a2b8dab55e',
    messagingSenderId: '225265442811',
    projectId: 'placenext-17bb0',
    authDomain: 'placenext-17bb0.firebaseapp.com',
    storageBucket: 'placenext-17bb0.appspot.com',
  );
}
